export const projects = [
  {
    title: 'Nie Tattoo Studio Website',
    description: "A responsive website for a professional tattoo artist, built using HTML, CSS, Bootstrap, and JavaScript. The site includes an artist introduction, service details, and a contact form, all designed with a modern and clean layout for a smooth user experience across devices.",
    image: '/images/1.png',
    tags: ['HTML', 'CSS', 'JavaScript', 'Bootstrap'],
    source: 'https://github.com/hieunguyen601/yen-nhi-tattoo-website',
    visit: 'https://www.yennhitattoo.com/',
    id: 0,
  },
  {
    title: 'User Registration Form',
    description:"A responsive and modern user sign-up form created using HTML, CSS, and JavaScript. It includes fields for name, email, and password, with real-time input validation and user-friendly error messages. The form is styled for a clean, professional look and optimized for both desktop and mobile devices.",
    image: '/images/2.png',
    tags: ['HTML', 'CSS', 'JavaScript'],
    source: 'https://github.com/hieunguyen601/User-Sign-Up-Form-Component',
    visit: 'https://hieunguyen601.github.io/User-Sign-Up-Form-Component/',
    id: 1,
  },
  {
    title: 'Age Calculator',
    description: "A responsive web application built with HTML, CSS, and JavaScript that allows users to input their birthdate and instantly calculate their age in years, months, and days. The app includes input validation to prevent invalid or future dates, and displays dynamic results with a clean and user-friendly interface.",
    image: '/images/3.png',
    tags: ['HTML', 'CSS', 'HTML'],
    source: 'https://github.com/hieunguyen601/Age-Calculation-App',
    visit: 'https://hieunguyen601.github.io/Age-Calculation-App/',
    id: 2,
  },
  {
    title: 'To-Do List App',
    description: "A simple and interactive to-do list application built with HTML, CSS, and JavaScript. Users can add, delete, and mark tasks as completed. Tasks are managed dynamically using JavaScript, with a clean UI and responsive layout. This project demonstrates DOM manipulation, event handling, and basic front-end logic.",
    image: '/images/4.png',
    tags: ['HTML', 'CSS', 'JavaScript'],
    source: 'https://github.com/hieunguyen601/JS-to-do-list',
    visit: 'https://hieunguyen601.github.io/JS-to-do-list/',
    id: 3,
  },
];
